name: Beaver-Auth CI/CD Pipeline

on:
  push:
    branches: [Main, master]
    tags:
      - 'v*'
  pull_request:
    branches: [Main, master]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v7

      - name: Setup pnpm and node.js
        uses: pnpm/setup@v1
        with:
          runtime: node@24
          install: true
          cache: true

      - name: Run tests (Vitest)
        run: pnpm -r test

      - name: Build core package only
        run: pnpm --filter @beaver-auth/core run build

  publish:
    needs: test-and-build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v7

      - name: Install pnpm
        uses: pnpm/setup@v1
        with:
          runtime: node@24
          install: true
          cache: true

      - name: Build Core Package Only
        run: pnpm --filter @beaver-auth/core run build

      - name: Publish Core Package Only
        run: pnpm --filter @beaver-auth/core publish --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.beaver_auth_npm_token }}
